SystemOutGirlsAlgorithm/algorithm

2022-05-11/leetcode_217_unpieceof.py
2022-05-11/leetcode_53(dp)_unpieceof.py
2022-05-11/leetcode_53_unpieceof.py

LeetCode 217 Contains Duplicate
LeetCode 53 Maximum Subarray (동적계획법, Best Solution 참고)
[[Data Structure] 2주 코스](https://leetcode.com/study-plan/data-structure/?progress=81jvahh)를 시작하였습니다.

LeetCode 217, 53 - 유감

---

2022-05-10/baekjoon_1075_muer.java
2022-05-11/baekjoon_1085_muer.java
2022-05-12/baekjoon_1233_muer.java

conflict가 발생해서 삭제하고 다시 fork 했습니다

백준 1075 나누기 - Muer

---

2022-05-11/baekjoon_10820_aning.js
2022-05-11/baekjoon_1850_aning.js
2022-05-12/baekjoon_9613_aning.js

백준 10820 문자열 분석, 1850 최대공약수, 9613 GCD 합 - 안잉
5월 둘째주 알고리즘 문제 풀이 코드입니다:)!🐥

백준 10820 문자열 분석, 1850 최대공약수, 9613 GCD 합 - 안잉

---

2022-05-13/leetcode_88(ms)_unpieceof.py

LeetCode 88.Merge Sorted Array를 다른 방식으로 풀어보았습니다.
- nums1과 nums2를 합친 후 일괄 sort
- Merge Sort 활용
: 의외로 Merge Sort 방식이 일괄 sort()보다 시간이 더 오래 걸렸음. nums1, nums2의 길이가 200 이하로 적은 편이어서 그런가?

LeetCode 88 Merge Sorted Array(2) - 유감

---

2022-05-15/leetcode_9_doris.js

입력된 정수가 회문인지 여부를 확인하는 문제였습니다.
- 정수를 string으로 변환한 후 가운데 글자부터 양 옆 글자들이 같은지 계속 확인해 나간다.
- 만약 다르면 바로 false를 리턴, 같다면 다음 글자들을 확인해야하기 때문에 continue로 for문을 빠져나가지 않게 해준다.
- for문이 끝나면 모두 같다는 것이기 때문에 true를 리턴한다.

LeetCode 9 Palindrome Number - 미도리

---

2022-05-15/programmers_K번째수_OoO

Add: 프로그래머스_K번째수_OoO

---

2022-05-16/leetcode_350(counter)_unpieceof.py
2022-05-16/leetcode_350_unpieceof.py

LeetCode [350](https://leetcode.com/problems/intersection-of-two-arrays-ii/) Intersection of Two Arrays II
두 가지 방법으로 풀어보았습니다. 
- 완전탐색 : O(n^2)
- Counter 사용 : O(n)

LeetCode 350 Intersection of Two Arrays II - 유감

---

2022-05-22/leetcode_566(list)_unpieceof.py
2022-05-22/leetcode_566(numpy)_unpieceof.py
2022-05-22/leetcode_566_unpieceof.py

LeetCode [566](https://leetcode.com/problems/reshape-the-matrix) Reshape the Matrix
세 가지 방법으로 풀어보았습니다.
- Bruteforce + numpy
- numpy(reshape)
- list comprehension

LeetCode 566 Reshape the Matrix - 유감

---

2022-06-03/leetcode_242_유감.py
2022-06-03/leetcode_383_유감.py

LeetCode 383 Ransom Note
LeetCode 242. Valid Anagram
- Counter() 활용하여 해결
- string array 관련 문제의 경우 Counter로 해결되는 경우가 많음

LeetCode 383 Ransom Note - 유감

---

2022-06-08/baekjoon_2004_안잉.js
2022-06-09/baekjoon_1676_안잉.js

백준 2004 조합 0의 개수 - 안잉
백준 1676 팩토리얼 0의 개수 - 안잉
수고하셨습니다:)!!🐥❄️

6월 2주차 알고리즘 문제 풀이

---

2022-06-13/baekjoon_6588_안잉.js
2022-06-14/baekjoon_2751_안잉.js
2022-06-15/baekjoon_11650_안잉.js
2022-06-16/baekjoon_11651_안잉.js
2022-06-18/baekjoon_10171_안잉.js

백준 6588 골드바흐의 추측 - 안잉
백준 2751 수 정렬하기 2 - 안잉
백준 11650 좌표 정렬하기 - 안잉
백준 11651 좌표 정렬하기 2 - 안잉
백준 10171 고양이 - 안잉
수고하셨습니다!! 🐱

6월 3주 알고리즘 문제 풀이 - 안잉

---

compute.py

- 특정 기간동안 문제 수를 확인하는 스크립트를 추가했습니다
- `yyyy-mm-dd`을 입력 해서 기간을 표현합니다. 
1. 특정 기간 동안의 폴더 목록을 읽는다 (2022-05-23 부터 2022-05-29)
2. 해당 폴더의 문제를 읽는다 (2022-05-24의 문제 - programmers_N개의최소공배수_Yoou.cpp)
3. 해당 문제의 닉네임을 파싱하여 문제 수를 센다
- 2022-05-23 ~ 2022-05-29 기간 동안의 폴더 목록을 조금 더 괜찮은 방법으로 읽어오도록 개선해야 합니다. 
- 변수명, 함수명 고치기
- 파일이 없는 경우 예외처리

Feat: 문제 수 계산하는 스크립트 추가

---

2022-06-23/baekjoon_10814_안잉.js
2022-06-23/baekjoon_10825_안잉.js
2022-06-24/programmers_x만큼간격이있는n개의숫자_안잉.js
2022-06-24/programmers_직사각형별찍기_안잉.js
2022-06-25/programmers_행렬의덧셈_안잉.js

백준 10814 나이순 정렬 - 안잉
백준 10825 국영수 - 안잉
프로그래머스 직사각형 별찍기 - 안잉
프로그래머스 x만큼 간격이 있는 n개의 숫자 - 안잉
프로그래머스 행렬의 덧셈 - 안잉
수고하셨습니다!! 🐥✨

6월 4주 알고리즘 문제 풀이 - 안잉

---

2022-06-27/programmers_하샤드수_안잉.js
2022-06-27/programmers_핸드폰번호가리기_안잉.js
2022-06-29/baekjoon_11652_안잉.js
2022-06-30/programmers_짝수와홀수.js
2022-06-30/programmers_최대공약수와최소공배수_안잉.js
2022-06-30/programmers_콜라츠추측_안잉.js
2022-06-30/programmers_평균구하기_안잉.js
2022-07-01/programmers_제일작은수제거하기.js
2022-07-02/baekjoon_11004_안잉.js
2022-07-02/programmers_정수제곱근판별_안잉.js

프로그래머스 핸드폰 번호 가리기 - 안잉
프로그래머스 하샤드 수 - 안잉
백준 11652 카드 - 안잉
프로그래머스 평균 구하기 - 안잉
프로그래머스 콜라츠 추측 - 안잉
프로그래머스 최대공약수와 최소공배수 - 안잉
프로그래머스 짝수와 홀수 - 안잉
프로그래머스 제일 작은 수 제거하기  - 안잉
프로그래머스 정수 제곱근 판별 - 안잉
백준 11004 K번째 수 - 안잉
수고하셨습니다!! 🐥✨

6월 5주차 알고리즘 문제 풀이

---

2022-07-09/baekjoon_1158_두괴풋.js

첫 pull request라 미숙해서 잘못 올린 부분이 있다면 디코에서 멘션 부탁드립니다!!

알고리즘 문제 풀이 올립니다(baekjoon1558_두괴풋)

---

2022-07-04/programmers_자연수뒤집어배열로만들기_안잉.js
2022-07-04/programmers_정수내림차순으로배치하기_안잉.js
2022-07-06/baekjoon_1654_안잉.js
2022-07-06/programmers_이상한문자만들기_안잉.js
2022-07-06/programmers_자연수더하기_안잉.js
2022-07-07/programmers_문자열을정수로바꾸기.js
2022-07-07/programmers_시저암호_안잉.js
2022-07-07/programmers_약수의합_안잉.js
2022-07-09/programmers_수박수박수박수박수박수_안잉.js

프로그래머스 정수 내림차순으로 배치하기 - 안잉
프로그래머스 자연수 뒤집어 배열로 만들기 - 안잉
프로그래머스 자연수 더하기 - 안잉
프로그래머스 이상한 문자 만들기 - 안잉
백준 1654 랜선 자르기 - 안잉
프로그래머스 약수의 합 - 안잉
프로그래머스 시저 암호 - 안잉
프로그래머스 문자열을 정수로 만들기 - 안잉
프로그래머스 수박수박수박수박수박수? - 안잉
7월 1주차 알고리즘 풀이입니다!
수고하셨습니다!🐥🔥

7월 1주차 알고리즘 풀이

---

2022-07-11/programmers_서울에서김서방찾기_안잉.js
2022-07-12/programmers_문자열다루기기본_안잉.js
2022-07-12/programmers_소수찾기_안잉.js
2022-07-13/baekjoon_2805_안잉.js
2022-07-13/programmers_문자열내p와y의개수_안잉.js
2022-07-13/programmers_문자열내림차순으로배치하기_안잉.js
2022-07-14/programmers_문자열내마음대로정렬하기_안잉.js
2022-07-15/programmers_두정수사이의합_안잉.js
2022-07-16/programmers_같은숫자는싫어_안잉.js
2022-07-17/programmers_나누어떨어지는숫자배열_안잉.js

프로그래머스 서울에서 김서방 찾기
프로그래서므 소수 찾기
프로그래머스 문자열 다루기 기본
프로그래머스 문자열 내림차순으로 배치하기
프로그래머스 문자열 내 p와 y의 개수
백준 2805 나무 자르기
프로그래머스 문자열 내 마음대로 정렬하기
프로그래머스 두 정수 사이의 합
프로그래머스 같은 숫자는 싫어
프로그래머스 나누어 떨어지는 숫자 배열
7월 2주차 알고리즘 풀이입니다!!🐥❄️

7월 2주차 알고리즘 풀이

---

2022-07-20/programmers_가운데글자가져오기_안잉.js
2022-07-21/programmers_2016년_안잉.js

프로그래머스 가운데 글자 가져오기
프로그래머스 2016년 
더 분발 하겠습니다 🥲🔥

7월 3주차 알고리즘 풀이

---

2022-07-31/baekjoon_11718_두괴풋.js
2022-07-31/baekjoon_11719_두괴풋_js
2022-07-31/baekjoon_11720_두괴풋.js
2022-07-31/baekjoon_11721_두괴풋.js
2022-07-31/baekjoon_2739_두괴풋.js
2022-07-31/baekjoon_2741_두괴풋.js
2022-07-31/baekjoon_2742_두괴풋.js
2022-07-31/baekjoon_8393_두괴풋.js

그동안 밀렸던 문제들 인증합니다.
저의 리퀘스트에 또 문제가 있다면 언제든 말씀해주세요!!
매번 감사합니당!

두괴풋 백준 문제 인증 완료

---

2022-07-25/programmers_다트게임_안잉.js
2022-07-26/programmers_비밀지도_안잉.js
2022-07-27/programmers_두개뽑아서더하기_안잉.js
2022-07-28/programmers_모의고사_안잉.js
2022-07-29/baekjoon_2110_안잉.js
2022-07-30/programmers_K번째수_안잉.js

프로그래머스 [1차] 다트게임
프로그래머스 [1차] 비밀지도
프로그래머스 두 개 뽑아서 더하기
프로그래머스 모의고사
백준 2110 공유기 설치
프로그래머스 K번째수
7월 4주차 알고리즘 풀이입니다!
수고하셨습니다👍✨

7월 4주차 알고리즘 풀이

---

2022-08-03/baekjoon_2438_두괴풋.js
2022-08-03/baekjoon_2439_두괴풋.js

백준 2438 2439 두괴풋 인증합니다!
문제 시 알려주세요 감사합니다

백준 2438 2439 두괴풋 인증

---

2022-08-05/programmers_신규아이디추천_뚜망.py

프로그래머스 신규아이디추천 - 뚜망

---

2022-08-06/baekjoon_2441_두괴풋.js

백준 2441 두괴풋 문제풀이 인증합니다!
문제 있을 시 알려주세요 감사합니다!

백준 2441 두괴풋 문제풀이 인증

---

2022-08-08/SWEA_1206_뚜망.py

SWEA 1206 View - 뚜망

---

2022-08-08/programmers_3진법뒤집기_안잉.js
2022-08-08/programmers_약수의개수와덧셈_안잉.js
2022-08-09/programmers_실패율_안잉.js
2022-08-11/programmers_완주하지못한선수_안잉.js

프로그래머스 3진법 뒤집기
프로그래머스 약수의 개수와 덧셈
프로그래머스 실패율
프로그래머스 완주하지 못한 선수
8월 2주차 알고리즘 문제 풀이 입니다!!✨

8월 2주차 알고리즘 풀이

---

2022-08-14/baekjoon_10250_릴리.java
2022-08-14/baekjoon_2775_릴리.java

8월 2주차 알고리즘 풀이 - 릴리

---

2022-08-08/baekjoon_9012_구름.cpp
2022-08-10/baekjoon_2480_구름.cpp
2022-08-11/baekjoon_10828_구름.cpp

금주는 야근 주출 때문에 참여가 힘들었네요 😥
이번 주는 힘내 보겠습니다! 고생하셨습니다~!

8월 2주차 알고리즘 풀이 - 구름

---

2022-08-15/baekjoon_2750_구름.cpp
2022-08-20/baekjoon_1712_구름.cpp

업무가 너무 바빠서 몇 문제 못 풀었네요 ㅠ_ㅠ 다음 주부터는 정상 참여하겠습니다!
한 주 고생 많으셨어요! 😊

8월 3주차 알고리즘 풀이 - 구름 

---

2022-08-15/programmers_체육복_안잉.js
2022-08-16/programmers_폰켓몬_안잉.js
2022-08-17/programmers_내적_안잉.js
2022-08-17/programmers_소수만들기_안잉.js
2022-08-18/programmers_없는숫자더하기_안잉.js
2022-08-19/programmers_크레인인형뽑기게임_안잉.js
2022-08-21/programmers_키패드누르기_안잉.js

프로그래머스 체육복
프로그래머스 폰켓몬
프로그래머스 소수 만들기
프로그래머스 내적
프로그래머스 없는 숫자 더하기
프로그래머스 크레인 인형뽑기 게임
프로그래머스 키패드 누르기
8월 3주차 알고리즘 풀이입니다🔥
수고하셨습니다! 좋은 밤 되세요!✨

8월 3주차 알고리즘 풀이

---

2022-08-16/baekjoon_2839_릴리.java
2022-08-21/baekjoon_10757_릴리.java

8월 3주차 - 릴리

---

2022-08-22/baekjoon_11650_구름.cpp
2022-08-23/baekjoon_2164_구름.cpp
2022-08-24/baekjoon_1427_구름.cpp
2022-08-27/baekjoon_10845_구름.cpp

8월 4주차 알고리즘 풀이 - 구름

---

2022-08-22/programmers_직사각형 별찍기_릴리.java
2022-08-28/programmers_x만큼 간격이 있는 n개의 숫자_릴리.java

8월 4주차 - 릴리

---

2022-08-22/programmers_숫자문자열과영단어_안잉.js
2022-08-23/programmer_신규아이디추천_안잉.js
2022-08-24/programmers_로또의최고순위와최저순위_안잉.js
2022-08-24/programmers_최소직사각형_안잉.js
2022-08-25/programmers_신고결과받기_안잉.js
2022-08-26/programmers_성격유형검사하기_안잉.js
2022-08-27/programmers_N개의최소공배수_안잉.js

프로그래머스 숫자 문자열과 영단어
프로그래머스 신규 아이디 추천
프로그래머스 로또의 최고 순위와 최저 순위
프로그래머스 최소직사각형
프로그래머스 신고 결과 받기
프로그래머스 성격 유형 검사하기
프로그래머스 N개의 최소 공배수
8월 4주차 알고리즘 문제 풀이 입니다!
이번 주차도 수고하셨습니다! ✨🔥

8월 4주차 알고리즘 문제 풀이

---

2022-09-03/baekjoon_11866_밍.cpp
2022-09-03/baekjoon_1920_밍.cpp

8월 5주차 알고리즘 스터디 - 밍

---

2022-08-29/programmers_행렬의곱셈_안잉.js
2022-08-30/programmers_JadenCase문자열만들기_안잉.js
2022-08-31/programmers_최댓값과최솟값_안잉.js
2022-09-02/programmers_피보나치수_안잉.js

이번주는 PR이 조금 늦었습니다 ㅜㅜ
프로그래머스 행렬의 곱셈
프로그래머스 JadenCase 문자열 만들기
프로그래머스 최댓값과 최솟값
프로그래머스 피보나치 수
8월 5주차 알고리즘 풀이입니다!
이번주도 수고 많으셨습니다!!!✨

8월 5주차 알고리즘 풀이

---

2022-09-11/programmers_나머지1_말챠.cpp
2022-09-11/programmers_자릿수더하기_말챠.cpp
2022-09-11/programmers_짝수와홀수_말챠.cpp

프로그래머스 Lv.1 나머지가 1이 되는 수 / 짝수와 홀수 / 자릿수 더하기

2022-09-11 말챠

---

2022-09-14/programmers_이진변환반복하기_안잉.js
2022-09-15/programmers_최솟값만들기_안잉.js
2022-09-16/programmers_올바른괄호_안잉.js

프로그래머스 이진 변환 반복하기
프로그래머스 최솟값 만들기
프로그래머스 올바른 괄호
9월 2주차 알고리즘 문제 풀이입니다!
이번주도 수고 많으셨습니다!! 🥰✨

9월 2주차 알고리즘 풀이

---

2022-09-19/programmers_숫자의표현_안잉.js
2022-09-20/programmers_다음큰숫자_안잉.js
2022-09-23/programmers_카펫_안잉.js

프로그래머스 숫자의 표현
프로그래머스 다음 큰 숫자
프로그래머스 카펫
9월 3주차 알고리즘 풀이입니다!!!!!!!
늦어서 죄송합니다!!! ㅜㅜㅜㅜ
다들 수고하셨습니다..! 👍

9월 3주차 알고리즘 풀이

---

2022-10-01/leetcode_205_밍.cpp
2022-10-01/leetcode_392_밍.cpp
2022-10-02/leetcode_206_밍.cpp
2022-10-02/leetcode_21_밍.cpp
2022-10-02/leetcode_876_밍.cpp

10월 1일부터 시작한다고 생각했는데, 아직 9월 4주차가 안 끝났네요! 이번 주 코드 제출합니다.

9월 4주차 알고리즘 스터디 - 밍

---

10월/2022-10-03/leetcode_142_밍.cpp
10월/2022-10-03/leetcode_234_밍.cpp
10월/2022-10-04/leetcode_121_밍.cpp
10월/2022-10-04/leetcode_409_밍.cpp
10월/2022-10-05/leetcode_102_밍.cpp
10월/2022-10-05/leetcode_589_밍.cpp
10월/2022-10-06/leetcode_278_밍.cpp
10월/2022-10-06/leetcode_704_밍.cpp
10월/2022-10-07/leetcode_235_밍.cpp
10월/2022-10-07/leetcode_98_밍.cpp

10월부터 폴더 구조가 변경된 줄 몰라서 코드를 하루에 몰아서 올린 사람이 되어버렸네요..! ㅠ_ㅠ

10월 1주차 알고리즘 스터디 - 밍
